name: crosvm-build

on:
  # push:
  #   branches: 
  #     - master
  # schedule:
  #   - cron: 0 20 * * *
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Install Build Tools
      run : |
        sudo -E apt-get update --fix-missing
        sudo -E apt-get -y install build-essential libncurses5-dev libcap-dev libfdt-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        
    - name: Clean
      run : |
        rm -rf crosvm
        rm -rf third_party/adhd
        rm -rf minijail
        
    - name: Download latest Crosvm
      run: |
        git config --global user.email "calinyara@gmail.com"
        git config --global user.name "Calinyara"
        
        git submodule add https://android.googlesource.com/platform/external/minijail
        git submodule add https://chromium.googlesource.com/chromiumos/platform/crosvm ./platform/crosvm
        git submodule add https://chromium.googlesource.com/chromiumos/third_party/adhd ./third_party/adhd
        
    # - name: Push Commits
    #  env:
    #    DOWNSTREAM_BRANCH: master
    #  run: |
    #    git add -A
    #    git push origin $DOWNSTREAM_BRANCH

    - name: Build Crosvm
      run: |
        cd minijail
        make clean
        make
        cd ..
        cd platform/crosvm
        cargo clean
        LIBRARY_PATH=../../minijail cargo build --release
        cd ../..

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: crosvm-binary
        path: platform/crosvm/target/release/
